### ISSUE TITLE
Default Store Code can not be loaded

### ISSUE THREAD

**Issue by mklooss** [customgento/module-default-store-code-remover-m2#1]
Hey there,

i've found out, that on the default Store we do not get correct store code.

in the Default Magento you do not get an real error:
https://github.com/magento/magento2/blob/c74256b9c637ac9808f8b0877d895b4a9b44f90f/app/code/Magento/Store/Model/StoreRepository.php#L63

when you debug the variable $code you will get an wrong result.

eg, the current Routername like customer / catalog and so on.

**Comment by sprankhub** [comment]
To be honest, I cannot follow. Can you share concrete steps to reproduce and explain why you think our module is related to this?

**Comment by sprankhub** [comment]
Closing this due to lack of feedback. Feel free to re-open with more information if this is still relevant, @mklooss :)
