### ISSUE TITLE
Module should also redirect not only remove the store code

### ISSUE THREAD

**Issue by cptX** [customgento/module-default-store-code-remover-m2#5]
Hi, it's unbelievable how such an important function is not included in magento core. Removing the store code for the default store is very important in many cases. For example I have a site in greek (el) and english (en) language, and for user friendliness and SEO I would like the default language to not be shown in the url.

Now, your module correctly eliminates the store code for the default store view for all corresponding links but doesn't redirect
from the www.example.com/el/page to www.example.com/page so we still have duplicate content, because both urls now give the same page!!

So your module actually is doing the half of the job!
Any chance to fix it?

**Comment by sprankhub** [comment]
That is not necessarily an issue if you used this module right from the beginning :) To be honest, I do not see this being implemented as part of this module. In the end, it can be achieved with a rather simple htaccess rule like the following:

    RewriteRule ^/el/(.*)$ /$1 [L,NC,R=301]

I hope this works for you.
