### ISSUE TITLE
Homepage language not correct

### ISSUE THREAD

**Issue by xavitriu** [customgento/module-default-store-code-remover-m2#7]
My site works correctly with your module.
example.com/ -> default language Spanish
example.com/en/ --> language English

After some days, example.com/ shows english page.

We cleared the admin cache and the site works fine again.
Maybe there is a problem with the cache? any idea what could happen?

**Comment by sprankhub** [comment]
Sorry, but I do not think this has anything to do with our module. And at the moment, I do not have a good idea regarding this.
